target_data maker scripts, related to issue #1
reichlab/variant-nowcast-model-dev-retro pull request #7
Opened 2024-11-23 17:43 UTC by IsaacMacarthur

Related to issue #1. These two scripts give two different approaches to creating the target_data files from the full metadata file. Quoting from my post on issue #1 "the first version target_data_maker.R just uses write_parquet to write a dataset for each Monday between 2022-08-01 and 2024-08-05 that contains all the sequences that were submitted by that Monday. The second version target_data_maker_v2.R instead creates a partition of the dataset where each file contains all the sequences that were submitted between two of the target dates; i.e the 2022-08-08 file would contain all the sequences submitted between 2022-08-01 and 2022-08-08, with the first file containing all sequences submitted before 2022-08-01.
The first approach stores more data and stores duplicates, but it makes it easy to load in the exact dataset we want for a given time point. The second approach doesn't store any duplicate data points, but it makes it harder to get the dataset for a given date, because you may need to sum many files to get the full dataset for that date." Please let me know what you think, and tell me which method you prefer.

2024-11-23 18:08 UTC, trobacker commented
Nice! To test this, can you also add the files/paths, e.g. `"./input-data/full_metadata_2024-11-22.tsv.zst"` to the PR for testing? Assuming it's not a ginormous file that will fill the repo lol.

2024-11-25 14:03 UTC, IsaacMacarthur commented
I just recommitted. Now by default the files will run a 100Ksample test case with the 100Ksample file now being part of the commit.

2024-11-25 22:01 UTC, nickreich requested changes
This is a great start at things! Thanks for making this pass, and for giving the two options for aggregation.

Here is my feedback
1. I suggest removing the sample file from the PR. We should figure out a better way to do this than putting the sample file in there. I'll look into LFS options for the full metadata file.
2. I prefer the first option (NOT v2). It's better to just have each dataset as a version "as_of" a specific date. then that dataset can be loaded, without any additional aggregation needed.
3. when using the `write_dataset()` function in the v2 script, you end up with files that are `as_of=2027-07-08/part-0.parquet`. If I understand correctly, this is then a "correctly specified" hive-partitioned dataset. When using your "v1" version of the script, I'd write files out in this exact same way, that way later on it could be read as a full partitioned dataset, which could have advantages later on.

2024-11-25 22:02 UTC, nickreich commented on src-data-processing/target_data_maker.R
> +full_data_file <- filter(full_data_file, date_submitted >= as.Date("2022-01-01"),
I would suggest merging this and the next set of lines that are doing data processing all into one single tidyverse-style piped together set of commands. Not an obligatory change, but more of a style thing.

2024-11-25 22:04 UTC, nickreich commented on src-data-processing/target_data_maker.R
> +full_data_file$Nextstrain_clade <- substr(full_data_file$Nextstrain_clade,1,3)
to make this code more compact, readable and in standard tidyverse style you could do something like
mutate(clade = ifelse(Nextstrain_clade == "recombinant", "recombinant", substr(Nextstrain_clade, 1, 3)))

2024-11-27 15:29 UTC, closed without merging

2024-11-27 15:29 UTC, nickreich commented
Closing this PR since it is superceded by #9